name: Build and Test

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/tmayoff/opendds_ros_infra
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          submodules: true

      - name: Setup ros workspace
        run: ./rmw_build/create_workspace.sh

      - uses: root-project/gcc-problem-matcher-improved@v0.0.1-alpha.1

      - name: Build all
        run: ./rmw_build/build_all.sh

      - name: Run CI tests
        run: ./rmw_build/run_ci_tests.sh
