name: Build and Test

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/tmayoff/opendds_ros_infra
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          submodules: true

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Setup ros workspace
        run: ./rmw_build/create_workspace.sh

      - uses: root-project/gcc-problem-matcher-improved@v0.0.1-alpha.1

      - run: rosdep update && make rosdep

      - name: Build all
        run: ./rmw_build/build_all.sh

      - name: Run CI tests
        shell: bash
        run: |
          source .envrc \
          cargo run -p ci_tests
